var searchData=
[
  ['abs_0',['ABS',['../../../dg/html/structdg_1_1_a_b_s.html',1,'dg']]],
  ['absmax_1',['AbsMax',['../../../dg/html/structdg_1_1_abs_max.html',1,'dg']]],
  ['absmin_2',['AbsMin',['../../../dg/html/structdg_1_1_abs_min.html',1,'dg']]],
  ['acylindricalfunctor_3',['aCylindricalFunctor',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bfieldp_20_3e_4',['aCylindricalFunctor&lt; BFieldP &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bfieldr_20_3e_5',['aCylindricalFunctor&lt; BFieldR &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bfieldt_20_3e_6',['aCylindricalFunctor&lt; BFieldT &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bfieldz_20_3e_7',['aCylindricalFunctor&lt; BFieldZ &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bhatp_20_3e_8',['aCylindricalFunctor&lt; BHatP &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bhatpr_20_3e_9',['aCylindricalFunctor&lt; BHatPR &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bhatpz_20_3e_10',['aCylindricalFunctor&lt; BHatPZ &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bhatr_20_3e_11',['aCylindricalFunctor&lt; BHatR &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bhatrr_20_3e_12',['aCylindricalFunctor&lt; BHatRR &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bhatrz_20_3e_13',['aCylindricalFunctor&lt; BHatRZ &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bhatz_20_3e_14',['aCylindricalFunctor&lt; BHatZ &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bhatzr_20_3e_15',['aCylindricalFunctor&lt; BHatZR &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bhatzz_20_3e_16',['aCylindricalFunctor&lt; BHatZZ &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bmodule_20_3e_17',['aCylindricalFunctor&lt; Bmodule &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20br_20_3e_18',['aCylindricalFunctor&lt; BR &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20bz_20_3e_19',['aCylindricalFunctor&lt; BZ &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20constant_20_3e_20',['aCylindricalFunctor&lt; Constant &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20curvaturekappar_20_3e_21',['aCylindricalFunctor&lt; CurvatureKappaR &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20curvaturekappaz_20_3e_22',['aCylindricalFunctor&lt; CurvatureKappaZ &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20curvaturenablabr_20_3e_23',['aCylindricalFunctor&lt; CurvatureNablaBR &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20curvaturenablabz_20_3e_24',['aCylindricalFunctor&lt; CurvatureNablaBZ &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20divb_20_3e_25',['aCylindricalFunctor&lt; Divb &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20divcurvaturekappa_20_3e_26',['aCylindricalFunctor&lt; DivCurvatureKappa &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20divcurvaturenablab_20_3e_27',['aCylindricalFunctor&lt; DivCurvatureNablaB &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20divliseikinx_20_3e_28',['aCylindricalFunctor&lt; DivLiseikinX &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20divliseikiny_20_3e_29',['aCylindricalFunctor&lt; DivLiseikinY &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20divvvp_20_3e_30',['aCylindricalFunctor&lt; DivVVP &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20gradlnb_20_3e_31',['aCylindricalFunctor&lt; GradLnB &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20hoo_20_3e_32',['aCylindricalFunctor&lt; Hoo &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20invb_20_3e_33',['aCylindricalFunctor&lt; InvB &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20ipol_20_3e_34',['aCylindricalFunctor&lt; Ipol &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20ipolr_20_3e_35',['aCylindricalFunctor&lt; IpolR &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20ipolz_20_3e_36',['aCylindricalFunctor&lt; IpolZ &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20laplacepsip_20_3e_37',['aCylindricalFunctor&lt; LaplacePsip &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20liseikin_5fxx_20_3e_38',['aCylindricalFunctor&lt; Liseikin_XX &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20liseikin_5fxy_20_3e_39',['aCylindricalFunctor&lt; Liseikin_XY &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20liseikin_5fyy_20_3e_40',['aCylindricalFunctor&lt; Liseikin_YY &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20lnb_20_3e_41',['aCylindricalFunctor&lt; LnB &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20nablapsiinv_20_3e_42',['aCylindricalFunctor&lt; NablaPsiInv &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20nablapsiinvx_20_3e_43',['aCylindricalFunctor&lt; NablaPsiInvX &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20nablapsiinvy_20_3e_44',['aCylindricalFunctor&lt; NablaPsiInvY &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20periodify_20_3e_45',['aCylindricalFunctor&lt; Periodify &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20psip_20_3e_46',['aCylindricalFunctor&lt; Psip &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20psipr_20_3e_47',['aCylindricalFunctor&lt; PsipR &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20psiprr_20_3e_48',['aCylindricalFunctor&lt; PsipRR &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20psiprz_20_3e_49',['aCylindricalFunctor&lt; PsipRZ &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20psipz_20_3e_50',['aCylindricalFunctor&lt; PsipZ &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20psipzz_20_3e_51',['aCylindricalFunctor&lt; PsipZZ &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20rhop_20_3e_52',['aCylindricalFunctor&lt; RhoP &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20scalarproduct_20_3e_53',['aCylindricalFunctor&lt; ScalarProduct &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20setcompose_20_3e_54',['aCylindricalFunctor&lt; SetCompose &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20setintersection_20_3e_55',['aCylindricalFunctor&lt; SetIntersection &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20setnot_20_3e_56',['aCylindricalFunctor&lt; SetNot &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20setunion_20_3e_57',['aCylindricalFunctor&lt; SetUnion &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20squarenorm_20_3e_58',['aCylindricalFunctor&lt; SquareNorm &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20truecurvaturekappap_20_3e_59',['aCylindricalFunctor&lt; TrueCurvatureKappaP &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20truecurvaturekappar_20_3e_60',['aCylindricalFunctor&lt; TrueCurvatureKappaR &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20truecurvaturekappaz_20_3e_61',['aCylindricalFunctor&lt; TrueCurvatureKappaZ &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20truecurvaturenablabp_20_3e_62',['aCylindricalFunctor&lt; TrueCurvatureNablaBP &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20truecurvaturenablabr_20_3e_63',['aCylindricalFunctor&lt; TrueCurvatureNablaBR &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20truecurvaturenablabz_20_3e_64',['aCylindricalFunctor&lt; TrueCurvatureNablaBZ &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20truedivcurvaturekappa_20_3e_65',['aCylindricalFunctor&lt; TrueDivCurvatureKappa &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20truedivcurvaturenablab_20_3e_66',['aCylindricalFunctor&lt; TrueDivCurvatureNablaB &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20walldirection_20_3e_67',['aCylindricalFunctor&lt; WallDirection &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20wallfieldlinecoordinate_20_3e_68',['aCylindricalFunctor&lt; WallFieldlineCoordinate &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20wallfieldlinedistance_20_3e_69',['aCylindricalFunctor&lt; WallFieldlineDistance &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['acylindricalfunctor_3c_20zcutter_20_3e_70',['aCylindricalFunctor&lt; ZCutter &gt;',['../structdg_1_1geo_1_1a_cylindrical_functor.html',1,'dg::geo']]],
  ['adaptive_71',['Adaptive',['../../../dg/html/structdg_1_1_adaptive.html',1,'dg']]],
  ['adaptivetimeloop_72',['AdaptiveTimeloop',['../../../dg/html/structdg_1_1_adaptive_timeloop.html',1,'dg']]],
  ['advection_73',['Advection',['../../../dg/html/structdg_1_1_advection.html',1,'dg']]],
  ['andersonacceleration_74',['AndersonAcceleration',['../../../dg/html/structdg_1_1_anderson_acceleration.html',1,'dg']]],
  ['anymatrixtag_75',['AnyMatrixTag',['../../../dg/html/structdg_1_1_any_matrix_tag.html',1,'dg']]],
  ['anypolicytag_76',['AnyPolicyTag',['../../../dg/html/structdg_1_1_any_policy_tag.html',1,'dg']]],
  ['anyscalartag_77',['AnyScalarTag',['../../../dg/html/structdg_1_1_any_scalar_tag.html',1,'dg']]],
  ['anyvectortag_78',['AnyVectorTag',['../../../dg/html/structdg_1_1_any_vector_tag.html',1,'dg']]],
  ['arakawax_79',['ArakawaX',['../../../dg/html/structdg_1_1_arakawa_x.html',1,'dg']]],
  ['arealgenerator2d_80',['aRealGenerator2d',['../structdg_1_1geo_1_1a_real_generator2d.html',1,'dg::geo']]],
  ['arealgeneratorx2d_81',['aRealGeneratorX2d',['../structdg_1_1geo_1_1a_real_generator_x2d.html',1,'dg::geo']]],
  ['arealgeometry2d_82',['aRealGeometry2d',['../../../dg/html/structdg_1_1a_real_geometry2d.html',1,'dg']]],
  ['arealgeometry2d_3c_20double_20_3e_83',['aRealGeometry2d&lt; double &gt;',['../../../dg/html/structdg_1_1a_real_geometry2d.html',1,'dg']]],
  ['arealgeometry2d_3c_20real_5ftype_20_3e_84',['aRealGeometry2d&lt; real_type &gt;',['../../../dg/html/structdg_1_1a_real_geometry2d.html',1,'dg']]],
  ['arealgeometry3d_85',['aRealGeometry3d',['../../../dg/html/structdg_1_1a_real_geometry3d.html',1,'dg']]],
  ['arealgeometry3d_3c_20real_5ftype_20_3e_86',['aRealGeometry3d&lt; real_type &gt;',['../../../dg/html/structdg_1_1a_real_geometry3d.html',1,'dg']]],
  ['arealgeometryx2d_87',['aRealGeometryX2d',['../../../dg/html/structdg_1_1a_real_geometry_x2d.html',1,'dg']]],
  ['arealgeometryx2d_3c_20real_5ftype_20_3e_88',['aRealGeometryX2d&lt; real_type &gt;',['../../../dg/html/structdg_1_1a_real_geometry_x2d.html',1,'dg']]],
  ['arealgeometryx3d_89',['aRealGeometryX3d',['../../../dg/html/structdg_1_1a_real_geometry_x3d.html',1,'dg']]],
  ['arealgeometryx3d_3c_20real_5ftype_20_3e_90',['aRealGeometryX3d&lt; real_type &gt;',['../../../dg/html/structdg_1_1a_real_geometry_x3d.html',1,'dg']]],
  ['arealmpigeometry2d_91',['aRealMPIGeometry2d',['../../../dg/html/structdg_1_1a_real_m_p_i_geometry2d.html',1,'dg']]],
  ['arealmpigeometry2d_3c_20real_5ftype_20_3e_92',['aRealMPIGeometry2d&lt; real_type &gt;',['../../../dg/html/structdg_1_1a_real_m_p_i_geometry2d.html',1,'dg']]],
  ['arealmpigeometry3d_93',['aRealMPIGeometry3d',['../../../dg/html/structdg_1_1a_real_m_p_i_geometry3d.html',1,'dg']]],
  ['arealmpigeometry3d_3c_20real_5ftype_20_3e_94',['aRealMPIGeometry3d&lt; real_type &gt;',['../../../dg/html/structdg_1_1a_real_m_p_i_geometry3d.html',1,'dg']]],
  ['arealmpitopology_95',['aRealMPITopology',['../../../dg/html/structdg_1_1a_real_m_p_i_topology.html',1,'dg']]],
  ['arealmpitopology_3c_20real_5ftype_2c_20nd_20_3e_96',['aRealMPITopology&lt; real_type, Nd &gt;',['../../../dg/html/structdg_1_1a_real_m_p_i_topology.html',1,'dg']]],
  ['arealproductgeometry3d_97',['aRealProductGeometry3d',['../../../dg/html/structdg_1_1a_real_product_geometry3d.html',1,'dg']]],
  ['arealproductgeometry3d_3c_20real_5ftype_20_3e_98',['aRealProductGeometry3d&lt; real_type &gt;',['../../../dg/html/structdg_1_1a_real_product_geometry3d.html',1,'dg']]],
  ['arealproductmpigeometry3d_99',['aRealProductMPIGeometry3d',['../../../dg/html/structdg_1_1a_real_product_m_p_i_geometry3d.html',1,'dg']]],
  ['arealproductmpigeometry3d_3c_20real_5ftype_20_3e_100',['aRealProductMPIGeometry3d&lt; real_type &gt;',['../../../dg/html/structdg_1_1a_real_product_m_p_i_geometry3d.html',1,'dg']]],
  ['arealrefinement1d_101',['aRealRefinement1d',['../../../dg/html/structdg_1_1a_real_refinement1d.html',1,'dg']]],
  ['arealrefinement1d_3c_20real_5ftype_20_3e_102',['aRealRefinement1d&lt; real_type &gt;',['../../../dg/html/structdg_1_1a_real_refinement1d.html',1,'dg']]],
  ['arealrefinementx2d_103',['aRealRefinementX2d',['../../../dg/html/structdg_1_1a_real_refinement_x2d.html',1,'dg']]],
  ['arealrefinementx2d_3c_20real_5ftype_20_3e_104',['aRealRefinementX2d&lt; real_type &gt;',['../../../dg/html/structdg_1_1a_real_refinement_x2d.html',1,'dg']]],
  ['arealtopology_105',['aRealTopology',['../../../dg/html/structdg_1_1a_real_topology.html',1,'dg']]],
  ['arealtopology_3c_20real_5ftype_2c_202_20_3e_106',['aRealTopology&lt; real_type, 2 &gt;',['../../../dg/html/structdg_1_1a_real_topology.html',1,'dg']]],
  ['arealtopology_3c_20real_5ftype_2c_203_20_3e_107',['aRealTopology&lt; real_type, 3 &gt;',['../../../dg/html/structdg_1_1a_real_topology.html',1,'dg']]],
  ['arealtopology_3c_20real_5ftype_2c_20nd_20_3e_108',['aRealTopology&lt; real_type, Nd &gt;',['../../../dg/html/structdg_1_1a_real_topology.html',1,'dg']]],
  ['arealtopologyx2d_109',['aRealTopologyX2d',['../../../dg/html/structdg_1_1a_real_topology_x2d.html',1,'dg']]],
  ['arealtopologyx2d_3c_20real_5ftype_20_3e_110',['aRealTopologyX2d&lt; real_type &gt;',['../../../dg/html/structdg_1_1a_real_topology_x2d.html',1,'dg']]],
  ['arealtopologyx3d_111',['aRealTopologyX3d',['../../../dg/html/structdg_1_1a_real_topology_x3d.html',1,'dg']]],
  ['arealtopologyx3d_3c_20real_5ftype_20_3e_112',['aRealTopologyX3d&lt; real_type &gt;',['../../../dg/html/structdg_1_1a_real_topology_x3d.html',1,'dg']]],
  ['arithmetictag_113',['ArithmeticTag',['../../../dg/html/structdg_1_1_arithmetic_tag.html',1,'dg']]],
  ['arkstep_114',['ARKStep',['../../../dg/html/structdg_1_1_a_r_k_step.html',1,'dg']]],
  ['arrayscalartag_115',['ArrayScalarTag',['../../../dg/html/structdg_1_1_array_scalar_tag.html',1,'dg']]],
  ['arrayvectortag_116',['ArrayVectorTag',['../../../dg/html/structdg_1_1_array_vector_tag.html',1,'dg']]],
  ['atimeloop_117',['aTimeloop',['../../../dg/html/structdg_1_1a_timeloop.html',1,'dg']]],
  ['atimeloop_3c_20containertype_20_3e_118',['aTimeloop&lt; ContainerType &gt;',['../../../dg/html/structdg_1_1a_timeloop.html',1,'dg']]],
  ['average_119',['Average',['../../../dg/html/structdg_1_1_average.html',1,'dg']]]
];
