var searchData=
[
  ['scalar_5fcategories_2eh_0',['scalar_categories.h',['../../../dg/html/scalar__categories_8h.html',1,'']]],
  ['separatrix_5forthogonal_2eh_1',['separatrix_orthogonal.h',['../separatrix__orthogonal_8h.html',1,'']]],
  ['sheath_2eh_2',['sheath.h',['../sheath_8h.html',1,'']]],
  ['simple_5forthogonal_2eh_3',['simple_orthogonal.h',['../simple__orthogonal_8h.html',1,'']]],
  ['simpsons_2eh_4',['simpsons.h',['../../../dg/html/simpsons_8h.html',1,'']]],
  ['solovev_2eh_5',['solovev.h',['../solovev_8h.html',1,'']]],
  ['solovev_5fparameters_2eh_6',['solovev_parameters.h',['../solovev__parameters_8h.html',1,'']]],
  ['sparseblockmat_2eh_7',['sparseblockmat.h',['../../../dg/html/sparseblockmat_8h.html',1,'']]],
  ['sparseblockmat_5fcpu_5fkernels_2eh_8',['sparseblockmat_cpu_kernels.h',['../../../dg/html/sparseblockmat__cpu__kernels_8h.html',1,'']]],
  ['sparsematrix_2eh_9',['sparsematrix.h',['../../../dg/html/sparsematrix_8h.html',1,'']]],
  ['sparsematrix_5fcpu_2eh_10',['sparsematrix_cpu.h',['../../../dg/html/sparsematrix__cpu_8h.html',1,'']]],
  ['sparsematrix_5fgpu_2ecuh_11',['sparsematrix_gpu.cuh',['../../../dg/html/sparsematrix__gpu_8cuh.html',1,'']]],
  ['sparsematrix_5fomp_2eh_12',['sparsematrix_omp.h',['../../../dg/html/sparsematrix__omp_8h.html',1,'']]],
  ['split_5fand_5fjoin_2eh_13',['split_and_join.h',['../../../dg/html/split__and__join_8h.html',1,'']]],
  ['stencil_2eh_14',['stencil.h',['../../../dg/html/stencil_8h.html',1,'']]],
  ['subroutines_2eh_15',['subroutines.h',['../../../dg/html/subroutines_8h.html',1,'']]]
];
