var searchData=
[
  ['tag_20dispatch_20system_0',['The tag dispatch system',['../../../dg/html/group__dispatch.html',1,'']]],
  ['taylor_20state_20expansion_1',['The Taylor state expansion',['../group__taylor.html',1,'']]],
  ['tensor_20operations_2',['Geometric grids and tensor operations',['../../../dg/html/group__geometry.html',1,'']]],
  ['tensor_20vector_20operations_3',['Tensor-Vector operations',['../../../dg/html/group__tensor.html',1,'']]],
  ['tensortraits_20specialisations_4',['All TensorTraits specialisations',['../../../dg/html/group__traits.html',1,'']]],
  ['terms_5',['Advection terms',['../../../dg/html/group__arakawa.html',1,'']]],
  ['the_20circular_20expansion_6',['The Circular expansion',['../group__circular.html',1,'']]],
  ['the_20guenter_20expansion_7',['The Guenter expansion',['../group__guenter.html',1,'']]],
  ['the_20magnetic_20field_20geometry_8',['3. New functors surrounding the magnetic field geometry',['../group__geom__functors.html',1,'']]],
  ['the_20polynomial_20expansion_9',['The polynomial expansion',['../group__polynomial.html',1,'']]],
  ['the_20purely_20toroidal_20expansion_10',['The Purely Toroidal expansion',['../group__toroidal.html',1,'']]],
  ['the_20solovev_20expansion_11',['The solovev expansion',['../group__solovev.html',1,'']]],
  ['the_20tag_20dispatch_20system_12',['The tag dispatch system',['../../../dg/html/group__dispatch.html',1,'']]],
  ['the_20taylor_20state_20expansion_13',['The Taylor state expansion',['../group__taylor.html',1,'']]],
  ['timer_20class_14',['Timer class',['../../../dg/html/group__timer.html',1,'']]],
  ['topological_20grids_20and_20operations_15',['Topological grids and operations',['../../../dg/html/group__grid.html',1,'']]],
  ['topology_20and_20geometry_16',['Level 3: Topology and Geometry',['../../../dg/html/group__level3.html',1,'']]],
  ['toroidal_20expansion_17',['The Purely Toroidal expansion',['../group__toroidal.html',1,'']]],
  ['transformation_18',['Interpolation, Projection, Transformation',['../../../dg/html/group__interpolation.html',1,'']]],
  ['two_20or_20more_20functors_19',['Composition of two or more functors',['../../../dg/html/group__composition.html',1,'']]],
  ['typedefs_20',['Grid Typedefs',['../../../dg/html/group__gridtypes.html',1,'']]],
  ['typedefs_20for_20vectors_20and_20matrices_21',['Typedefs for Vectors and Matrices',['../../../dg/html/group__typedefs.html',1,'']]]
];
