var files_dup =
[
    [ "exp_runge_kutta.h", "exp__runge__kutta_8h.html", null ],
    [ "exp_runge_kutta_t.cpp", "exp__runge__kutta__t_8cpp.html", "exp__runge__kutta__t_8cpp" ],
    [ "functors.h", "functors_8h.html", "functors_8h" ],
    [ "functors_t.cpp", "functors__t_8cpp.html", "functors__t_8cpp" ],
    [ "invtridiag_t.cpp", "invtridiag__t_8cpp.html", "invtridiag__t_8cpp" ],
    [ "lanczos.h", "lanczos_8h.html", null ],
    [ "lanczos_b.cpp", "lanczos__b_8cpp.html", "lanczos__b_8cpp" ],
    [ "lanczos_mpib.cpp", "lanczos__mpib_8cpp.html", "lanczos__mpib_8cpp" ],
    [ "matrix.h", "matrix_8h.html", null ],
    [ "matrix_doc.h", "matrix__doc_8h.html", null ],
    [ "matrixfunction.h", "matrixfunction_8h.html", "matrixfunction_8h" ],
    [ "matrixfunction_b.cpp", "matrixfunction__b_8cpp.html", "matrixfunction__b_8cpp" ],
    [ "matrixsqrt.h", "matrixsqrt_8h.html", null ],
    [ "matrixsqrt_b.cpp", "matrixsqrt__b_8cpp.html", "matrixsqrt__b_8cpp" ],
    [ "mcg.h", "mcg_8h.html", null ],
    [ "polarization.h", "polarization_8h.html", null ],
    [ "polarization_b.cpp", "polarization__b_8cpp.html", "polarization__b_8cpp" ],
    [ "polarization_init.h", "polarization__init_8h.html", "polarization__init_8h" ],
    [ "polarization_init_t.cpp", "polarization__init__t_8cpp.html", "polarization__init__t_8cpp" ],
    [ "sqrt_cauchy.h", "sqrt__cauchy_8h.html", "sqrt__cauchy_8h" ],
    [ "sqrt_ode.h", "sqrt__ode_8h.html", "sqrt__ode_8h" ],
    [ "tableau.h", "tableau_8h.html", "tableau_8h" ],
    [ "tensorelliptic.h", "tensorelliptic_8h.html", null ],
    [ "tensorelliptic2d_b.cpp", "tensorelliptic2d__b_8cpp.html", "tensorelliptic2d__b_8cpp" ],
    [ "tridiaginv.h", "tridiaginv_8h.html", "tridiaginv_8h" ],
    [ "tridiaginv_b.cpp", "tridiaginv__b_8cpp.html", "tridiaginv__b_8cpp" ]
];