var annotated_dup =
[
    [ "dg", "namespacedg.html", [
      [ "detail", "namespacedg_1_1detail.html", [
        [ "CSRCache_cpu", "structdg_1_1detail_1_1_c_s_r_cache__cpu.html", "structdg_1_1detail_1_1_c_s_r_cache__cpu" ],
        [ "CSRCache_gpu", "structdg_1_1detail_1_1_c_s_r_cache__gpu.html", "structdg_1_1detail_1_1_c_s_r_cache__gpu" ],
        [ "CSRCache_omp", "structdg_1_1detail_1_1_c_s_r_cache__omp.html", "structdg_1_1detail_1_1_c_s_r_cache__omp" ],
        [ "CusparseError", "structdg_1_1detail_1_1_cusparse_error.html", "structdg_1_1detail_1_1_cusparse_error" ],
        [ "CusparseErrorHandle", "structdg_1_1detail_1_1_cusparse_error_handle.html", "structdg_1_1detail_1_1_cusparse_error_handle" ],
        [ "CusparseHandle", "structdg_1_1detail_1_1_cusparse_handle.html", "structdg_1_1detail_1_1_cusparse_handle" ]
      ] ],
      [ "ABS", "structdg_1_1_a_b_s.html", "structdg_1_1_a_b_s" ],
      [ "AbsMax", "structdg_1_1_abs_max.html", "structdg_1_1_abs_max" ],
      [ "AbsMin", "structdg_1_1_abs_min.html", "structdg_1_1_abs_min" ],
      [ "Adaptive", "structdg_1_1_adaptive.html", "structdg_1_1_adaptive" ],
      [ "AdaptiveTimeloop", "structdg_1_1_adaptive_timeloop.html", "structdg_1_1_adaptive_timeloop" ],
      [ "Advection", "structdg_1_1_advection.html", "structdg_1_1_advection" ],
      [ "AndersonAcceleration", "structdg_1_1_anderson_acceleration.html", "structdg_1_1_anderson_acceleration" ],
      [ "AnyMatrixTag", "structdg_1_1_any_matrix_tag.html", null ],
      [ "AnyPolicyTag", "structdg_1_1_any_policy_tag.html", null ],
      [ "AnyScalarTag", "structdg_1_1_any_scalar_tag.html", null ],
      [ "AnyVectorTag", "structdg_1_1_any_vector_tag.html", null ],
      [ "ArakawaX", "structdg_1_1_arakawa_x.html", "structdg_1_1_arakawa_x" ],
      [ "aRealGeometry2d", "structdg_1_1a_real_geometry2d.html", "structdg_1_1a_real_geometry2d" ],
      [ "aRealGeometry3d", "structdg_1_1a_real_geometry3d.html", "structdg_1_1a_real_geometry3d" ],
      [ "aRealGeometryX2d", "structdg_1_1a_real_geometry_x2d.html", "structdg_1_1a_real_geometry_x2d" ],
      [ "aRealGeometryX3d", "structdg_1_1a_real_geometry_x3d.html", "structdg_1_1a_real_geometry_x3d" ],
      [ "aRealMPIGeometry2d", "structdg_1_1a_real_m_p_i_geometry2d.html", "structdg_1_1a_real_m_p_i_geometry2d" ],
      [ "aRealMPIGeometry3d", "structdg_1_1a_real_m_p_i_geometry3d.html", "structdg_1_1a_real_m_p_i_geometry3d" ],
      [ "aRealMPITopology", "structdg_1_1a_real_m_p_i_topology.html", "structdg_1_1a_real_m_p_i_topology" ],
      [ "aRealProductGeometry3d", "structdg_1_1a_real_product_geometry3d.html", "structdg_1_1a_real_product_geometry3d" ],
      [ "aRealProductMPIGeometry3d", "structdg_1_1a_real_product_m_p_i_geometry3d.html", "structdg_1_1a_real_product_m_p_i_geometry3d" ],
      [ "aRealRefinement1d", "structdg_1_1a_real_refinement1d.html", "structdg_1_1a_real_refinement1d" ],
      [ "aRealRefinementX2d", "structdg_1_1a_real_refinement_x2d.html", "structdg_1_1a_real_refinement_x2d" ],
      [ "aRealTopology", "structdg_1_1a_real_topology.html", "structdg_1_1a_real_topology" ],
      [ "aRealTopologyX2d", "structdg_1_1a_real_topology_x2d.html", "structdg_1_1a_real_topology_x2d" ],
      [ "aRealTopologyX3d", "structdg_1_1a_real_topology_x3d.html", "structdg_1_1a_real_topology_x3d" ],
      [ "ArithmeticTag", "structdg_1_1_arithmetic_tag.html", null ],
      [ "ARKStep", "structdg_1_1_a_r_k_step.html", "structdg_1_1_a_r_k_step" ],
      [ "ArrayScalarTag", "structdg_1_1_array_scalar_tag.html", null ],
      [ "ArrayVectorTag", "structdg_1_1_array_vector_tag.html", null ],
      [ "aTimeloop", "structdg_1_1a_timeloop.html", "structdg_1_1a_timeloop" ],
      [ "Average", "structdg_1_1_average.html", "structdg_1_1_average" ],
      [ "BathRZ", "structdg_1_1_bath_r_z.html", "structdg_1_1_bath_r_z" ],
      [ "BICGSTABl", "classdg_1_1_b_i_c_g_s_t_a_bl.html", "classdg_1_1_b_i_c_g_s_t_a_bl" ],
      [ "ButcherTableau", "structdg_1_1_butcher_tableau.html", "structdg_1_1_butcher_tableau" ],
      [ "Cauchy", "structdg_1_1_cauchy.html", "structdg_1_1_cauchy" ],
      [ "CauchyX", "structdg_1_1_cauchy_x.html", "structdg_1_1_cauchy_x" ],
      [ "ChebyshevIteration", "classdg_1_1_chebyshev_iteration.html", "classdg_1_1_chebyshev_iteration" ],
      [ "ChebyshevPreconditioner", "structdg_1_1_chebyshev_preconditioner.html", "structdg_1_1_chebyshev_preconditioner" ],
      [ "ClonePtr", "structdg_1_1_clone_ptr.html", "structdg_1_1_clone_ptr" ],
      [ "ComplexTag", "structdg_1_1_complex_tag.html", null ],
      [ "Composite", "structdg_1_1_composite.html", "structdg_1_1_composite" ],
      [ "CONSTANT", "structdg_1_1_c_o_n_s_t_a_n_t.html", "structdg_1_1_c_o_n_s_t_a_n_t" ],
      [ "ConvertsToButcherTableau", "structdg_1_1_converts_to_butcher_tableau.html", "structdg_1_1_converts_to_butcher_tableau" ],
      [ "ConvertsToMultistepTableau", "structdg_1_1_converts_to_multistep_tableau.html", "structdg_1_1_converts_to_multistep_tableau" ],
      [ "ConvertsToShuOsherTableau", "structdg_1_1_converts_to_shu_osher_tableau.html", "structdg_1_1_converts_to_shu_osher_tableau" ],
      [ "CooSparseBlockMat", "structdg_1_1_coo_sparse_block_mat.html", "structdg_1_1_coo_sparse_block_mat" ],
      [ "CosXCosY", "structdg_1_1_cos_x_cos_y.html", "structdg_1_1_cos_x_cos_y" ],
      [ "CosY", "structdg_1_1_cos_y.html", "structdg_1_1_cos_y" ],
      [ "CSRAverageFilter", "structdg_1_1_c_s_r_average_filter.html", "structdg_1_1_c_s_r_average_filter" ],
      [ "CSRMedianFilter", "structdg_1_1_c_s_r_median_filter.html", "structdg_1_1_c_s_r_median_filter" ],
      [ "CSRSlopeLimiter", "structdg_1_1_c_s_r_slope_limiter.html", "structdg_1_1_c_s_r_slope_limiter" ],
      [ "CSRSWMFilter", "structdg_1_1_c_s_r_s_w_m_filter.html", "structdg_1_1_c_s_r_s_w_m_filter" ],
      [ "CSRSymvFilter", "structdg_1_1_c_s_r_symv_filter.html", "structdg_1_1_c_s_r_symv_filter" ],
      [ "CudaTag", "structdg_1_1_cuda_tag.html", null ],
      [ "CuspMatrixTag", "structdg_1_1_cusp_matrix_tag.html", null ],
      [ "CuspVectorTag", "structdg_1_1_cusp_vector_tag.html", null ],
      [ "DefaultSolver", "structdg_1_1_default_solver.html", "structdg_1_1_default_solver" ],
      [ "DenseMatrixTag", "structdg_1_1_dense_matrix_tag.html", null ],
      [ "DIRKStep", "structdg_1_1_d_i_r_k_step.html", "structdg_1_1_d_i_r_k_step" ],
      [ "Distance", "structdg_1_1_distance.html", "structdg_1_1_distance" ],
      [ "divides_equals", "structdg_1_1divides__equals.html", "structdg_1_1divides__equals" ],
      [ "DLT", "structdg_1_1_d_l_t.html", "structdg_1_1_d_l_t" ],
      [ "DPolynomialHeaviside", "structdg_1_1_d_polynomial_heaviside.html", "structdg_1_1_d_polynomial_heaviside" ],
      [ "Elliptic1d", "classdg_1_1_elliptic1d.html", "classdg_1_1_elliptic1d" ],
      [ "Elliptic2d", "classdg_1_1_elliptic2d.html", "classdg_1_1_elliptic2d" ],
      [ "Elliptic3d", "classdg_1_1_elliptic3d.html", "classdg_1_1_elliptic3d" ],
      [ "EllSparseBlockMat", "structdg_1_1_ell_sparse_block_mat.html", "structdg_1_1_ell_sparse_block_mat" ],
      [ "EmbeddedPairSum", "structdg_1_1_embedded_pair_sum.html", "structdg_1_1_embedded_pair_sum" ],
      [ "EntireDomain", "structdg_1_1_entire_domain.html", "structdg_1_1_entire_domain" ],
      [ "equals", "structdg_1_1equals.html", "structdg_1_1equals" ],
      [ "ERKStep", "structdg_1_1_e_r_k_step.html", "structdg_1_1_e_r_k_step" ],
      [ "Error", "classdg_1_1_error.html", "classdg_1_1_error" ],
      [ "EVE", "classdg_1_1_e_v_e.html", "classdg_1_1_e_v_e" ],
      [ "EXP", "structdg_1_1_e_x_p.html", "structdg_1_1_e_x_p" ],
      [ "ExplicitMultistep", "structdg_1_1_explicit_multistep.html", "structdg_1_1_explicit_multistep" ],
      [ "ExponentialFilter", "structdg_1_1_exponential_filter.html", "structdg_1_1_exponential_filter" ],
      [ "ExpProfX", "structdg_1_1_exp_prof_x.html", "structdg_1_1_exp_prof_x" ],
      [ "Extrapolation", "structdg_1_1_extrapolation.html", "structdg_1_1_extrapolation" ],
      [ "Fail", "structdg_1_1_fail.html", "structdg_1_1_fail" ],
      [ "FilteredERKStep", "structdg_1_1_filtered_e_r_k_step.html", "structdg_1_1_filtered_e_r_k_step" ],
      [ "FilteredExplicitMultistep", "structdg_1_1_filtered_explicit_multistep.html", "structdg_1_1_filtered_explicit_multistep" ],
      [ "FloatingPointTag", "structdg_1_1_floating_point_tag.html", null ],
      [ "Gaussian", "structdg_1_1_gaussian.html", "structdg_1_1_gaussian" ],
      [ "Gaussian3d", "structdg_1_1_gaussian3d.html", "structdg_1_1_gaussian3d" ],
      [ "GaussianDamping", "structdg_1_1_gaussian_damping.html", "structdg_1_1_gaussian_damping" ],
      [ "GaussianX", "structdg_1_1_gaussian_x.html", "structdg_1_1_gaussian_x" ],
      [ "GaussianY", "structdg_1_1_gaussian_y.html", "structdg_1_1_gaussian_y" ],
      [ "GaussianZ", "structdg_1_1_gaussian_z.html", "structdg_1_1_gaussian_z" ],
      [ "GeneralHelmholtz", "structdg_1_1_general_helmholtz.html", "structdg_1_1_general_helmholtz" ],
      [ "Heaviside", "structdg_1_1_heaviside.html", "structdg_1_1_heaviside" ],
      [ "Helmholtz2", "structdg_1_1_helmholtz2.html", "structdg_1_1_helmholtz2" ],
      [ "Histogram", "structdg_1_1_histogram.html", "structdg_1_1_histogram" ],
      [ "Histogram2D", "structdg_1_1_histogram2_d.html", "structdg_1_1_histogram2_d" ],
      [ "Horner2d", "structdg_1_1_horner2d.html", "structdg_1_1_horner2d" ],
      [ "IDENTITY", "structdg_1_1_i_d_e_n_t_i_t_y.html", "structdg_1_1_i_d_e_n_t_i_t_y" ],
      [ "IdentityFilter", "structdg_1_1_identity_filter.html", "structdg_1_1_identity_filter" ],
      [ "ImExMultistep", "structdg_1_1_im_ex_multistep.html", "structdg_1_1_im_ex_multistep" ],
      [ "ImplicitMultistep", "structdg_1_1_implicit_multistep.html", "structdg_1_1_implicit_multistep" ],
      [ "IntegralTag", "structdg_1_1_integral_tag.html", null ],
      [ "InvCoshXsq", "structdg_1_1_inv_cosh_xsq.html", "structdg_1_1_inv_cosh_xsq" ],
      [ "InverseKroneckerTriDiagonal2d", "structdg_1_1_inverse_kronecker_tri_diagonal2d.html", "structdg_1_1_inverse_kronecker_tri_diagonal2d" ],
      [ "InverseTriDiagonal", "structdg_1_1_inverse_tri_diagonal.html", "structdg_1_1_inverse_tri_diagonal" ],
      [ "INVERT", "structdg_1_1_i_n_v_e_r_t.html", "structdg_1_1_i_n_v_e_r_t" ],
      [ "InvSqrt", "structdg_1_1_inv_sqrt.html", "structdg_1_1_inv_sqrt" ],
      [ "IPolynomialHeaviside", "structdg_1_1_i_polynomial_heaviside.html", "structdg_1_1_i_polynomial_heaviside" ],
      [ "Iris", "structdg_1_1_iris.html", "structdg_1_1_iris" ],
      [ "IslandXY", "structdg_1_1_island_x_y.html", "structdg_1_1_island_x_y" ],
      [ "ISNFINITE", "structdg_1_1_i_s_n_f_i_n_i_t_e.html", "structdg_1_1_i_s_n_f_i_n_i_t_e" ],
      [ "ISNSANE", "structdg_1_1_i_s_n_s_a_n_e.html", "structdg_1_1_i_s_n_s_a_n_e" ],
      [ "KroneckerTriDiagonal2d", "structdg_1_1_kronecker_tri_diagonal2d.html", "structdg_1_1_kronecker_tri_diagonal2d" ],
      [ "Lamb", "structdg_1_1_lamb.html", "structdg_1_1_lamb" ],
      [ "LeastSquaresExtrapolation", "structdg_1_1_least_squares_extrapolation.html", "structdg_1_1_least_squares_extrapolation" ],
      [ "LeastSquaresPreconditioner", "structdg_1_1_least_squares_preconditioner.html", "structdg_1_1_least_squares_preconditioner" ],
      [ "LGMRES", "classdg_1_1_l_g_m_r_e_s.html", "classdg_1_1_l_g_m_r_e_s" ],
      [ "Line", "structdg_1_1_line.html", "structdg_1_1_line" ],
      [ "LinearX", "structdg_1_1_linear_x.html", "structdg_1_1_linear_x" ],
      [ "LinearY", "structdg_1_1_linear_y.html", "structdg_1_1_linear_y" ],
      [ "LinearZ", "structdg_1_1_linear_z.html", "structdg_1_1_linear_z" ],
      [ "LN", "structdg_1_1_l_n.html", "structdg_1_1_l_n" ],
      [ "Message", "classdg_1_1_message.html", "classdg_1_1_message" ],
      [ "MinMod", "structdg_1_1_min_mod.html", "structdg_1_1_min_mod" ],
      [ "minus_equals", "structdg_1_1minus__equals.html", "structdg_1_1minus__equals" ],
      [ "MOD", "structdg_1_1_m_o_d.html", "structdg_1_1_m_o_d" ],
      [ "ModifiedChebyshevPreconditioner", "structdg_1_1_modified_chebyshev_preconditioner.html", "structdg_1_1_modified_chebyshev_preconditioner" ],
      [ "MPI_Vector", "structdg_1_1_m_p_i___vector.html", "structdg_1_1_m_p_i___vector" ],
      [ "MPIDistMat", "structdg_1_1_m_p_i_dist_mat.html", "structdg_1_1_m_p_i_dist_mat" ],
      [ "MPIGather", "structdg_1_1_m_p_i_gather.html", "structdg_1_1_m_p_i_gather" ],
      [ "MPIKroneckerGather", "structdg_1_1_m_p_i_kronecker_gather.html", "structdg_1_1_m_p_i_kronecker_gather" ],
      [ "MPIMatrixTag", "structdg_1_1_m_p_i_matrix_tag.html", null ],
      [ "MPISparseBlockMat", "structdg_1_1_m_p_i_sparse_block_mat.html", "structdg_1_1_m_p_i_sparse_block_mat" ],
      [ "MPIVectorTag", "structdg_1_1_m_p_i_vector_tag.html", null ],
      [ "MultigridCG2d", "structdg_1_1_multigrid_c_g2d.html", "structdg_1_1_multigrid_c_g2d" ],
      [ "MultiMatrix", "structdg_1_1_multi_matrix.html", "structdg_1_1_multi_matrix" ],
      [ "MultistepTableau", "structdg_1_1_multistep_tableau.html", "structdg_1_1_multistep_tableau" ],
      [ "MultistepTimeloop", "structdg_1_1_multistep_timeloop.html", "structdg_1_1_multistep_timeloop" ],
      [ "NestedGrids", "structdg_1_1_nested_grids.html", "structdg_1_1_nested_grids" ],
      [ "NoPolicyTag", "structdg_1_1_no_policy_tag.html", null ],
      [ "NoRoot1d", "classdg_1_1_no_root1d.html", "classdg_1_1_no_root1d" ],
      [ "NotATensorTag", "structdg_1_1_not_a_tensor_tag.html", null ],
      [ "OmpTag", "structdg_1_1_omp_tag.html", null ],
      [ "ONE", "structdg_1_1_o_n_e.html", "structdg_1_1_o_n_e" ],
      [ "PairSum", "structdg_1_1_pair_sum.html", "structdg_1_1_pair_sum" ],
      [ "PCG", "classdg_1_1_p_c_g.html", "classdg_1_1_p_c_g" ],
      [ "PLUS", "structdg_1_1_p_l_u_s.html", "structdg_1_1_p_l_u_s" ],
      [ "plus_equals", "structdg_1_1plus__equals.html", "structdg_1_1plus__equals" ],
      [ "Poisson", "structdg_1_1_poisson.html", "structdg_1_1_poisson" ],
      [ "PolynomialHeaviside", "structdg_1_1_polynomial_heaviside.html", "structdg_1_1_polynomial_heaviside" ],
      [ "PolynomialRectangle", "structdg_1_1_polynomial_rectangle.html", "structdg_1_1_polynomial_rectangle" ],
      [ "POSVALUE", "structdg_1_1_p_o_s_v_a_l_u_e.html", "structdg_1_1_p_o_s_v_a_l_u_e" ],
      [ "Product", "structdg_1_1_product.html", "structdg_1_1_product" ],
      [ "PsiPupil", "structdg_1_1_psi_pupil.html", "structdg_1_1_psi_pupil" ],
      [ "Pupil", "structdg_1_1_pupil.html", "structdg_1_1_pupil" ],
      [ "RealCartesianGrid2d", "structdg_1_1_real_cartesian_grid2d.html", "structdg_1_1_real_cartesian_grid2d" ],
      [ "RealCartesianGrid3d", "structdg_1_1_real_cartesian_grid3d.html", "structdg_1_1_real_cartesian_grid3d" ],
      [ "RealCartesianGridX2d", "structdg_1_1_real_cartesian_grid_x2d.html", "structdg_1_1_real_cartesian_grid_x2d" ],
      [ "RealCartesianGridX3d", "structdg_1_1_real_cartesian_grid_x3d.html", "structdg_1_1_real_cartesian_grid_x3d" ],
      [ "RealCartesianMPIGrid2d", "structdg_1_1_real_cartesian_m_p_i_grid2d.html", "structdg_1_1_real_cartesian_m_p_i_grid2d" ],
      [ "RealCartesianMPIGrid3d", "structdg_1_1_real_cartesian_m_p_i_grid3d.html", "structdg_1_1_real_cartesian_m_p_i_grid3d" ],
      [ "RealCartesianRefinedGrid2d", "structdg_1_1_real_cartesian_refined_grid2d.html", "structdg_1_1_real_cartesian_refined_grid2d" ],
      [ "RealCartesianRefinedGrid3d", "structdg_1_1_real_cartesian_refined_grid3d.html", "structdg_1_1_real_cartesian_refined_grid3d" ],
      [ "RealCartesianRefinedGridX2d", "structdg_1_1_real_cartesian_refined_grid_x2d.html", "structdg_1_1_real_cartesian_refined_grid_x2d" ],
      [ "RealCartesianRefinedGridX3d", "structdg_1_1_real_cartesian_refined_grid_x3d.html", "structdg_1_1_real_cartesian_refined_grid_x3d" ],
      [ "RealCylindricalGrid3d", "structdg_1_1_real_cylindrical_grid3d.html", "structdg_1_1_real_cylindrical_grid3d" ],
      [ "RealCylindricalMPIGrid3d", "structdg_1_1_real_cylindrical_m_p_i_grid3d.html", "structdg_1_1_real_cylindrical_m_p_i_grid3d" ],
      [ "RealEquidistRefinement", "structdg_1_1_real_equidist_refinement.html", "structdg_1_1_real_equidist_refinement" ],
      [ "RealEquidistXRefinement", "structdg_1_1_real_equidist_x_refinement.html", "structdg_1_1_real_equidist_x_refinement" ],
      [ "RealExponentialRefinement", "structdg_1_1_real_exponential_refinement.html", "structdg_1_1_real_exponential_refinement" ],
      [ "RealExponentialXRefinement", "structdg_1_1_real_exponential_x_refinement.html", "structdg_1_1_real_exponential_x_refinement" ],
      [ "RealFemRefinement", "structdg_1_1_real_fem_refinement.html", "structdg_1_1_real_fem_refinement" ],
      [ "RealGrid", "structdg_1_1_real_grid.html", "structdg_1_1_real_grid" ],
      [ "RealGridX1d", "structdg_1_1_real_grid_x1d.html", "structdg_1_1_real_grid_x1d" ],
      [ "RealGridX2d", "structdg_1_1_real_grid_x2d.html", "structdg_1_1_real_grid_x2d" ],
      [ "RealGridX3d", "structdg_1_1_real_grid_x3d.html", "structdg_1_1_real_grid_x3d" ],
      [ "RealIdentityRefinement", "structdg_1_1_real_identity_refinement.html", "structdg_1_1_real_identity_refinement" ],
      [ "RealIdentityXRefinement", "structdg_1_1_real_identity_x_refinement.html", "structdg_1_1_real_identity_x_refinement" ],
      [ "RealLinearRefinement", "structdg_1_1_real_linear_refinement.html", "structdg_1_1_real_linear_refinement" ],
      [ "RealMPIGrid", "structdg_1_1_real_m_p_i_grid.html", "structdg_1_1_real_m_p_i_grid" ],
      [ "RecursiveVectorTag", "structdg_1_1_recursive_vector_tag.html", null ],
      [ "RefinedElliptic", "classdg_1_1_refined_elliptic.html", "classdg_1_1_refined_elliptic" ],
      [ "SelfMadeMatrixTag", "structdg_1_1_self_made_matrix_tag.html", null ],
      [ "SerialTag", "structdg_1_1_serial_tag.html", null ],
      [ "SharedVectorTag", "structdg_1_1_shared_vector_tag.html", null ],
      [ "ShuOsher", "structdg_1_1_shu_osher.html", "structdg_1_1_shu_osher" ],
      [ "ShuOsherTableau", "structdg_1_1_shu_osher_tableau.html", "structdg_1_1_shu_osher_tableau" ],
      [ "Sign", "structdg_1_1_sign.html", "structdg_1_1_sign" ],
      [ "Simpsons", "structdg_1_1_simpsons.html", "structdg_1_1_simpsons" ],
      [ "SinglestepTimeloop", "structdg_1_1_singlestep_timeloop.html", "structdg_1_1_singlestep_timeloop" ],
      [ "SinProfX", "structdg_1_1_sin_prof_x.html", "structdg_1_1_sin_prof_x" ],
      [ "SinX", "structdg_1_1_sin_x.html", "structdg_1_1_sin_x" ],
      [ "SinXCosY", "structdg_1_1_sin_x_cos_y.html", "structdg_1_1_sin_x_cos_y" ],
      [ "SinXSinY", "structdg_1_1_sin_x_sin_y.html", "structdg_1_1_sin_x_sin_y" ],
      [ "SinY", "structdg_1_1_sin_y.html", "structdg_1_1_sin_y" ],
      [ "SlopeLimiter", "structdg_1_1_slope_limiter.html", "structdg_1_1_slope_limiter" ],
      [ "SlopeLimiterProduct", "structdg_1_1_slope_limiter_product.html", "structdg_1_1_slope_limiter_product" ],
      [ "SparseBlockMatrixTag", "structdg_1_1_sparse_block_matrix_tag.html", null ],
      [ "SparseMatrix", "structdg_1_1_sparse_matrix.html", "structdg_1_1_sparse_matrix" ],
      [ "SparseMatrixTag", "structdg_1_1_sparse_matrix_tag.html", null ],
      [ "SparseTensor", "structdg_1_1_sparse_tensor.html", "structdg_1_1_sparse_tensor" ],
      [ "SQRT", "structdg_1_1_s_q_r_t.html", "structdg_1_1_s_q_r_t" ],
      [ "Square", "structdg_1_1_square.html", "structdg_1_1_square" ],
      [ "SquareMatrix", "classdg_1_1_square_matrix.html", "classdg_1_1_square_matrix" ],
      [ "StdMapTag", "structdg_1_1_std_map_tag.html", null ],
      [ "Sum", "structdg_1_1_sum.html", "structdg_1_1_sum" ],
      [ "TanhProfX", "structdg_1_1_tanh_prof_x.html", "structdg_1_1_tanh_prof_x" ],
      [ "TensorTraits", "structdg_1_1_tensor_traits.html", "structdg_1_1_tensor_traits" ],
      [ "TensorTraits< CooSparseBlockMat< T, V > >", "structdg_1_1_tensor_traits_3_01_coo_sparse_block_mat_3_01_t_00_01_v_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01_coo_sparse_block_mat_3_01_t_00_01_v_01_4_01_4" ],
      [ "TensorTraits< cusp::coo_matrix< I, V, M > >", "structdg_1_1_tensor_traits_3_01cusp_1_1coo__matrix_3_01_i_00_01_v_00_01_m_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01cusp_1_1coo__matrix_3_01_i_00_01_v_00_01_m_01_4_01_4" ],
      [ "TensorTraits< cusp::csr_matrix< I, V, M > >", "structdg_1_1_tensor_traits_3_01cusp_1_1csr__matrix_3_01_i_00_01_v_00_01_m_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01cusp_1_1csr__matrix_3_01_i_00_01_v_00_01_m_01_4_01_4" ],
      [ "TensorTraits< cusp::dia_matrix< I, V, M > >", "structdg_1_1_tensor_traits_3_01cusp_1_1dia__matrix_3_01_i_00_01_v_00_01_m_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01cusp_1_1dia__matrix_3_01_i_00_01_v_00_01_m_01_4_01_4" ],
      [ "TensorTraits< cusp::ell_matrix< I, V, M > >", "structdg_1_1_tensor_traits_3_01cusp_1_1ell__matrix_3_01_i_00_01_v_00_01_m_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01cusp_1_1ell__matrix_3_01_i_00_01_v_00_01_m_01_4_01_4" ],
      [ "TensorTraits< cusp::hyb_matrix< I, V, M > >", "structdg_1_1_tensor_traits_3_01cusp_1_1hyb__matrix_3_01_i_00_01_v_00_01_m_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01cusp_1_1hyb__matrix_3_01_i_00_01_v_00_01_m_01_4_01_4" ],
      [ "TensorTraits< EllSparseBlockMat< T, V > >", "structdg_1_1_tensor_traits_3_01_ell_sparse_block_mat_3_01_t_00_01_v_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01_ell_sparse_block_mat_3_01_t_00_01_v_01_4_01_4" ],
      [ "TensorTraits< MPI_Vector< container > >", "structdg_1_1_tensor_traits_3_01_m_p_i___vector_3_01container_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01_m_p_i___vector_3_01container_01_4_01_4" ],
      [ "TensorTraits< MPIDistMat< V, LI, LO > >", "structdg_1_1_tensor_traits_3_01_m_p_i_dist_mat_3_01_v_00_01_l_i_00_01_l_o_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01_m_p_i_dist_mat_3_01_v_00_01_l_i_00_01_l_o_01_4_01_4" ],
      [ "TensorTraits< MPISparseBlockMat< V, LI, LO > >", "structdg_1_1_tensor_traits_3_01_m_p_i_sparse_block_mat_3_01_v_00_01_l_i_00_01_l_o_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01_m_p_i_sparse_block_mat_3_01_v_00_01_l_i_00_01_l_o_01_4_01_4" ],
      [ "TensorTraits< SparseMatrix< I, T, V > >", "structdg_1_1_tensor_traits_3_01_sparse_matrix_3_01_i_00_01_t_00_01_v_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01_sparse_matrix_3_01_i_00_01_t_00_01_v_01_4_01_4" ],
      [ "TensorTraits< SquareMatrix< T > >", "structdg_1_1_tensor_traits_3_01_square_matrix_3_01_t_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01_square_matrix_3_01_t_01_4_01_4" ],
      [ "TensorTraits< std::array< T, N >, std::enable_if_t< !dg::is_scalar< T >::value > >", "structdg_1_1_tensor_traits_3_01std_1_1array_3_01_t_00_01_n_01_4_00_01std_1_1enable__if__t_3_01_9be759d623ffdbc8e87dee6970ed4642c.html", "structdg_1_1_tensor_traits_3_01std_1_1array_3_01_t_00_01_n_01_4_00_01std_1_1enable__if__t_3_01_9be759d623ffdbc8e87dee6970ed4642c" ],
      [ "TensorTraits< std::array< T, N >, std::enable_if_t< dg::is_scalar< T >::value > >", "structdg_1_1_tensor_traits_3_01std_1_1array_3_01_t_00_01_n_01_4_00_01std_1_1enable__if__t_3_01dg6961005f3bd0f5defbff6f8120c0b205.html", "structdg_1_1_tensor_traits_3_01std_1_1array_3_01_t_00_01_n_01_4_00_01std_1_1enable__if__t_3_01dg6961005f3bd0f5defbff6f8120c0b205" ],
      [ "TensorTraits< std::complex< T > >", "structdg_1_1_tensor_traits_3_01std_1_1complex_3_01_t_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01std_1_1complex_3_01_t_01_4_01_4" ],
      [ "TensorTraits< std::map< Key, T > >", "structdg_1_1_tensor_traits_3_01std_1_1map_3_01_key_00_01_t_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01std_1_1map_3_01_key_00_01_t_01_4_01_4" ],
      [ "TensorTraits< std::vector< T >, std::enable_if_t< !dg::is_scalar< T >::value > >", "structdg_1_1_tensor_traits_3_01std_1_1vector_3_01_t_01_4_00_01std_1_1enable__if__t_3_01_9dg_1_1i73b63978a49a63ec1ec8531993781f69.html", "structdg_1_1_tensor_traits_3_01std_1_1vector_3_01_t_01_4_00_01std_1_1enable__if__t_3_01_9dg_1_1i73b63978a49a63ec1ec8531993781f69" ],
      [ "TensorTraits< std::vector< T >, std::enable_if_t< dg::is_scalar< T >::value > >", "structdg_1_1_tensor_traits_3_01std_1_1vector_3_01_t_01_4_00_01std_1_1enable__if__t_3_01dg_1_1is_d3fab0ae6923a6be270aac89af686d01.html", "structdg_1_1_tensor_traits_3_01std_1_1vector_3_01_t_01_4_00_01std_1_1enable__if__t_3_01dg_1_1is_d3fab0ae6923a6be270aac89af686d01" ],
      [ "TensorTraits< T, std::enable_if_t< std::is_floating_point_v< T > > >", "structdg_1_1_tensor_traits_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__floating__point__v_3_01_t_01_4_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__floating__point__v_3_01_t_01_4_01_4_01_4" ],
      [ "TensorTraits< T, std::enable_if_t< std::is_integral_v< T > > >", "structdg_1_1_tensor_traits_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__integral__v_3_01_t_01_4_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__integral__v_3_01_t_01_4_01_4_01_4" ],
      [ "TensorTraits< thrust::complex< T > >", "structdg_1_1_tensor_traits_3_01thrust_1_1complex_3_01_t_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01thrust_1_1complex_3_01_t_01_4_01_4" ],
      [ "TensorTraits< thrust::device_vector< T > >", "structdg_1_1_tensor_traits_3_01thrust_1_1device__vector_3_01_t_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01thrust_1_1device__vector_3_01_t_01_4_01_4" ],
      [ "TensorTraits< thrust::host_vector< T > >", "structdg_1_1_tensor_traits_3_01thrust_1_1host__vector_3_01_t_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01thrust_1_1host__vector_3_01_t_01_4_01_4" ],
      [ "TensorTraits< View< ThrustVector > >", "structdg_1_1_tensor_traits_3_01_view_3_01_thrust_vector_01_4_01_4.html", "structdg_1_1_tensor_traits_3_01_view_3_01_thrust_vector_01_4_01_4" ],
      [ "ThrustVectorTag", "structdg_1_1_thrust_vector_tag.html", null ],
      [ "Timer", "structdg_1_1_timer.html", "structdg_1_1_timer" ],
      [ "times_equals", "structdg_1_1times__equals.html", "structdg_1_1times__equals" ],
      [ "TriDiagonal", "structdg_1_1_tri_diagonal.html", "structdg_1_1_tri_diagonal" ],
      [ "TripletSum", "structdg_1_1_triplet_sum.html", "structdg_1_1_triplet_sum" ],
      [ "Upwind", "structdg_1_1_upwind.html", "structdg_1_1_upwind" ],
      [ "UpwindProduct", "structdg_1_1_upwind_product.html", "structdg_1_1_upwind_product" ],
      [ "VanLeer", "structdg_1_1_van_leer.html", "structdg_1_1_van_leer" ],
      [ "View", "structdg_1_1_view.html", "structdg_1_1_view" ],
      [ "Vortex", "structdg_1_1_vortex.html", "structdg_1_1_vortex" ],
      [ "WallDistance", "structdg_1_1_wall_distance.html", "structdg_1_1_wall_distance" ],
      [ "WhichType", "structdg_1_1_which_type.html", null ],
      [ "ZERO", "structdg_1_1_z_e_r_o.html", "structdg_1_1_z_e_r_o" ]
    ] ]
];