var files_dup =
[
    [ "backend", "dir_8c739bbef76d64b22d6b0911c526dd76.html", "dir_8c739bbef76d64b22d6b0911c526dd76" ],
    [ "topology", "dir_84497794bb37d283dbd68163bed8ef05.html", "dir_84497794bb37d283dbd68163bed8ef05" ],
    [ "adaptive.h", "adaptive_8h.html", "adaptive_8h" ],
    [ "advection.h", "advection_8h.html", null ],
    [ "algorithm.h", "algorithm_8h.html", null ],
    [ "andersonacc.h", "andersonacc_8h.html", "andersonacc_8h" ],
    [ "arakawa.h", "arakawa_8h.html", null ],
    [ "bicgstabl.h", "bicgstabl_8h.html", null ],
    [ "blas.h", "blas_8h.html", null ],
    [ "blas1.h", "blas1_8h.html", "blas1_8h" ],
    [ "blas2.h", "blas2_8h.html", "blas2_8h" ],
    [ "chebyshev.h", "chebyshev_8h.html", null ],
    [ "dg_doc.h", "dg__doc_8h.html", "dg__doc_8h" ],
    [ "elliptic.h", "elliptic_8h.html", "elliptic_8h" ],
    [ "enums.h", "enums_8h.html", "enums_8h" ],
    [ "eve.h", "eve_8h.html", null ],
    [ "extrapolation.h", "extrapolation_8h.html", "extrapolation_8h" ],
    [ "functors.h", "functors_8h.html", "functors_8h" ],
    [ "helmholtz.h", "helmholtz_8h.html", "helmholtz_8h" ],
    [ "implicit.h", "implicit_8h.html", null ],
    [ "lgmres.h", "lgmres_8h.html", null ],
    [ "multigrid.h", "multigrid_8h.html", "multigrid_8h" ],
    [ "multistep.h", "multistep_8h.html", null ],
    [ "multistep_tableau.h", "multistep__tableau_8h.html", "multistep__tableau_8h" ],
    [ "nullstelle.h", "nullstelle_8h.html", "nullstelle_8h" ],
    [ "ode.h", "ode_8h.html", "ode_8h" ],
    [ "pcg.h", "pcg_8h.html", null ],
    [ "poisson.h", "poisson_8h.html", null ],
    [ "refined_elliptic.h", "refined__elliptic_8h.html", null ],
    [ "runge_kutta.h", "runge__kutta_8h.html", "runge__kutta_8h" ],
    [ "simpsons.h", "simpsons_8h.html", null ],
    [ "subroutines.h", "subroutines_8h.html", "subroutines_8h" ],
    [ "tableau.h", "tableau_8h.html", "tableau_8h" ]
];