var searchData=
[
  ['elliptic1d_0',['Elliptic1d',['../classdg_1_1_elliptic1d.html',1,'dg']]],
  ['elliptic2d_1',['Elliptic2d',['../classdg_1_1_elliptic2d.html',1,'dg']]],
  ['elliptic3d_2',['Elliptic3d',['../classdg_1_1_elliptic3d.html',1,'dg']]],
  ['ellsparseblockmat_3',['EllSparseBlockMat',['../structdg_1_1_ell_sparse_block_mat.html',1,'dg']]],
  ['embeddedpairsum_4',['EmbeddedPairSum',['../structdg_1_1_embedded_pair_sum.html',1,'dg']]],
  ['entiredomain_5',['EntireDomain',['../structdg_1_1_entire_domain.html',1,'dg']]],
  ['equals_6',['equals',['../structdg_1_1equals.html',1,'dg']]],
  ['erkstep_7',['ERKStep',['../structdg_1_1_e_r_k_step.html',1,'dg']]],
  ['error_8',['Error',['../classdg_1_1_error.html',1,'dg']]],
  ['eve_9',['EVE',['../classdg_1_1_e_v_e.html',1,'dg']]],
  ['exp_10',['EXP',['../structdg_1_1_e_x_p.html',1,'dg']]],
  ['explicitmultistep_11',['ExplicitMultistep',['../structdg_1_1_explicit_multistep.html',1,'dg']]],
  ['exponentialerkstep_12',['ExponentialERKStep',['../../../matrix/html/structdg_1_1mat_1_1_exponential_e_r_k_step.html',1,'dg::mat']]],
  ['exponentialfilter_13',['ExponentialFilter',['../structdg_1_1_exponential_filter.html',1,'dg']]],
  ['exponentialstep_14',['ExponentialStep',['../../../matrix/html/structdg_1_1mat_1_1_exponential_step.html',1,'dg::mat']]],
  ['expprofx_15',['ExpProfX',['../structdg_1_1_exp_prof_x.html',1,'dg']]],
  ['extrapolation_16',['Extrapolation',['../structdg_1_1_extrapolation.html',1,'dg']]]
];
