var searchData=
[
  ['tag_20dispatch_20system_0',['The tag dispatch system',['../group__dispatch.html',1,'']]],
  ['taylor_20state_20expansion_1',['The Taylor state expansion',['../../../geometries/html/group__taylor.html',1,'']]],
  ['tensor_20operations_2',['Geometric grids and tensor operations',['../group__geometry.html',1,'']]],
  ['tensor_20vector_20operations_3',['Tensor-Vector operations',['../group__tensor.html',1,'']]],
  ['tensortraits_20specialisations_4',['All TensorTraits specialisations',['../group__traits.html',1,'']]],
  ['terms_5',['Advection terms',['../group__arakawa.html',1,'']]],
  ['the_20circular_20expansion_6',['The Circular expansion',['../../../geometries/html/group__circular.html',1,'']]],
  ['the_20guenter_20expansion_7',['The Guenter expansion',['../../../geometries/html/group__guenter.html',1,'']]],
  ['the_20magnetic_20field_20geometry_8',['3. New functors surrounding the magnetic field geometry',['../../../geometries/html/group__geom__functors.html',1,'']]],
  ['the_20polynomial_20expansion_9',['The polynomial expansion',['../../../geometries/html/group__polynomial.html',1,'']]],
  ['the_20purely_20toroidal_20expansion_10',['The Purely Toroidal expansion',['../../../geometries/html/group__toroidal.html',1,'']]],
  ['the_20solovev_20expansion_11',['The solovev expansion',['../../../geometries/html/group__solovev.html',1,'']]],
  ['the_20tag_20dispatch_20system_12',['The tag dispatch system',['../group__dispatch.html',1,'']]],
  ['the_20taylor_20state_20expansion_13',['The Taylor state expansion',['../../../geometries/html/group__taylor.html',1,'']]],
  ['timer_20class_14',['Timer class',['../group__timer.html',1,'']]],
  ['topological_20grids_20and_20operations_15',['Topological grids and operations',['../group__grid.html',1,'']]],
  ['topology_20and_20geometry_16',['Level 3: Topology and Geometry',['../group__level3.html',1,'']]],
  ['toroidal_20expansion_17',['The Purely Toroidal expansion',['../../../geometries/html/group__toroidal.html',1,'']]],
  ['transformation_18',['Interpolation, Projection, Transformation',['../group__interpolation.html',1,'']]],
  ['tridiagonal_20matrices_19',['Inversion of tridiagonal matrices',['../../../matrix/html/group__matrixinvert.html',1,'']]],
  ['tridiagonal_20matrix_20functions_20',['Tridiagonal Matrix-functions',['../../../matrix/html/group__tridiagfunction.html',1,'']]],
  ['two_20or_20more_20functors_21',['Composition of two or more functors',['../group__composition.html',1,'']]],
  ['typedefs_22',['Grid Typedefs',['../group__gridtypes.html',1,'']]],
  ['typedefs_20for_20vectors_20and_20matrices_23',['Typedefs for Vectors and Matrices',['../group__typedefs.html',1,'']]]
];
