var annotated_dup =
[
    [ "dg", null, [
      [ "geo", "namespacedg_1_1geo.html", [
        [ "circular", "namespacedg_1_1geo_1_1circular.html", [
          [ "Psip", "structdg_1_1geo_1_1circular_1_1_psip.html", "structdg_1_1geo_1_1circular_1_1_psip" ],
          [ "PsipR", "structdg_1_1geo_1_1circular_1_1_psip_r.html", "structdg_1_1geo_1_1circular_1_1_psip_r" ],
          [ "PsipZ", "structdg_1_1geo_1_1circular_1_1_psip_z.html", "structdg_1_1geo_1_1circular_1_1_psip_z" ]
        ] ],
        [ "guenter", "namespacedg_1_1geo_1_1guenter.html", [
          [ "Ipol", "structdg_1_1geo_1_1guenter_1_1_ipol.html", "structdg_1_1geo_1_1guenter_1_1_ipol" ],
          [ "IpolR", "structdg_1_1geo_1_1guenter_1_1_ipol_r.html", "structdg_1_1geo_1_1guenter_1_1_ipol_r" ],
          [ "IpolZ", "structdg_1_1geo_1_1guenter_1_1_ipol_z.html", "structdg_1_1geo_1_1guenter_1_1_ipol_z" ],
          [ "Psip", "structdg_1_1geo_1_1guenter_1_1_psip.html", "structdg_1_1geo_1_1guenter_1_1_psip" ],
          [ "PsipR", "structdg_1_1geo_1_1guenter_1_1_psip_r.html", "structdg_1_1geo_1_1guenter_1_1_psip_r" ],
          [ "PsipRR", "structdg_1_1geo_1_1guenter_1_1_psip_r_r.html", "structdg_1_1geo_1_1guenter_1_1_psip_r_r" ],
          [ "PsipRZ", "structdg_1_1geo_1_1guenter_1_1_psip_r_z.html", "structdg_1_1geo_1_1guenter_1_1_psip_r_z" ],
          [ "PsipZ", "structdg_1_1geo_1_1guenter_1_1_psip_z.html", "structdg_1_1geo_1_1guenter_1_1_psip_z" ],
          [ "PsipZZ", "structdg_1_1geo_1_1guenter_1_1_psip_z_z.html", "structdg_1_1geo_1_1guenter_1_1_psip_z_z" ]
        ] ],
        [ "mod", "namespacedg_1_1geo_1_1mod.html", [
          [ "ClosedFieldlineRegion", "structdg_1_1geo_1_1mod_1_1_closed_fieldline_region.html", "structdg_1_1geo_1_1mod_1_1_closed_fieldline_region" ],
          [ "Psip", "structdg_1_1geo_1_1mod_1_1_psip.html", "structdg_1_1geo_1_1mod_1_1_psip" ],
          [ "PsipR", "structdg_1_1geo_1_1mod_1_1_psip_r.html", "structdg_1_1geo_1_1mod_1_1_psip_r" ],
          [ "PsipRR", "structdg_1_1geo_1_1mod_1_1_psip_r_r.html", "structdg_1_1geo_1_1mod_1_1_psip_r_r" ],
          [ "PsipRZ", "structdg_1_1geo_1_1mod_1_1_psip_r_z.html", "structdg_1_1geo_1_1mod_1_1_psip_r_z" ],
          [ "PsipZ", "structdg_1_1geo_1_1mod_1_1_psip_z.html", "structdg_1_1geo_1_1mod_1_1_psip_z" ],
          [ "PsipZZ", "structdg_1_1geo_1_1mod_1_1_psip_z_z.html", "structdg_1_1geo_1_1mod_1_1_psip_z_z" ],
          [ "SetCompose", "structdg_1_1geo_1_1mod_1_1_set_compose.html", "structdg_1_1geo_1_1mod_1_1_set_compose" ],
          [ "SetIntersection", "structdg_1_1geo_1_1mod_1_1_set_intersection.html", "structdg_1_1geo_1_1mod_1_1_set_intersection" ],
          [ "SetNot", "structdg_1_1geo_1_1mod_1_1_set_not.html", "structdg_1_1geo_1_1mod_1_1_set_not" ],
          [ "SetUnion", "structdg_1_1geo_1_1mod_1_1_set_union.html", "structdg_1_1geo_1_1mod_1_1_set_union" ],
          [ "SOLRegion", "structdg_1_1geo_1_1mod_1_1_s_o_l_region.html", "structdg_1_1geo_1_1mod_1_1_s_o_l_region" ]
        ] ],
        [ "polynomial", "namespacedg_1_1geo_1_1polynomial.html", [
          [ "Parameters", "structdg_1_1geo_1_1polynomial_1_1_parameters.html", "structdg_1_1geo_1_1polynomial_1_1_parameters" ],
          [ "Psip", "structdg_1_1geo_1_1polynomial_1_1_psip.html", "structdg_1_1geo_1_1polynomial_1_1_psip" ],
          [ "PsipR", "structdg_1_1geo_1_1polynomial_1_1_psip_r.html", "structdg_1_1geo_1_1polynomial_1_1_psip_r" ],
          [ "PsipRR", "structdg_1_1geo_1_1polynomial_1_1_psip_r_r.html", "structdg_1_1geo_1_1polynomial_1_1_psip_r_r" ],
          [ "PsipRZ", "structdg_1_1geo_1_1polynomial_1_1_psip_r_z.html", "structdg_1_1geo_1_1polynomial_1_1_psip_r_z" ],
          [ "PsipZ", "structdg_1_1geo_1_1polynomial_1_1_psip_z.html", "structdg_1_1geo_1_1polynomial_1_1_psip_z" ],
          [ "PsipZZ", "structdg_1_1geo_1_1polynomial_1_1_psip_z_z.html", "structdg_1_1geo_1_1polynomial_1_1_psip_z_z" ]
        ] ],
        [ "solovev", "namespacedg_1_1geo_1_1solovev.html", [
          [ "Ipol", "structdg_1_1geo_1_1solovev_1_1_ipol.html", "structdg_1_1geo_1_1solovev_1_1_ipol" ],
          [ "IpolR", "structdg_1_1geo_1_1solovev_1_1_ipol_r.html", "structdg_1_1geo_1_1solovev_1_1_ipol_r" ],
          [ "IpolZ", "structdg_1_1geo_1_1solovev_1_1_ipol_z.html", "structdg_1_1geo_1_1solovev_1_1_ipol_z" ],
          [ "Parameters", "structdg_1_1geo_1_1solovev_1_1_parameters.html", "structdg_1_1geo_1_1solovev_1_1_parameters" ],
          [ "Psip", "structdg_1_1geo_1_1solovev_1_1_psip.html", "structdg_1_1geo_1_1solovev_1_1_psip" ],
          [ "PsipR", "structdg_1_1geo_1_1solovev_1_1_psip_r.html", "structdg_1_1geo_1_1solovev_1_1_psip_r" ],
          [ "PsipRR", "structdg_1_1geo_1_1solovev_1_1_psip_r_r.html", "structdg_1_1geo_1_1solovev_1_1_psip_r_r" ],
          [ "PsipRZ", "structdg_1_1geo_1_1solovev_1_1_psip_r_z.html", "structdg_1_1geo_1_1solovev_1_1_psip_r_z" ],
          [ "PsipZ", "structdg_1_1geo_1_1solovev_1_1_psip_z.html", "structdg_1_1geo_1_1solovev_1_1_psip_z" ],
          [ "PsipZZ", "structdg_1_1geo_1_1solovev_1_1_psip_z_z.html", "structdg_1_1geo_1_1solovev_1_1_psip_z_z" ]
        ] ],
        [ "taylor", "namespacedg_1_1geo_1_1taylor.html", [
          [ "Ipol", "structdg_1_1geo_1_1taylor_1_1_ipol.html", "structdg_1_1geo_1_1taylor_1_1_ipol" ],
          [ "IpolR", "structdg_1_1geo_1_1taylor_1_1_ipol_r.html", "structdg_1_1geo_1_1taylor_1_1_ipol_r" ],
          [ "IpolZ", "structdg_1_1geo_1_1taylor_1_1_ipol_z.html", "structdg_1_1geo_1_1taylor_1_1_ipol_z" ],
          [ "Psip", "structdg_1_1geo_1_1taylor_1_1_psip.html", "structdg_1_1geo_1_1taylor_1_1_psip" ],
          [ "PsipR", "structdg_1_1geo_1_1taylor_1_1_psip_r.html", "structdg_1_1geo_1_1taylor_1_1_psip_r" ],
          [ "PsipRR", "structdg_1_1geo_1_1taylor_1_1_psip_r_r.html", "structdg_1_1geo_1_1taylor_1_1_psip_r_r" ],
          [ "PsipRZ", "structdg_1_1geo_1_1taylor_1_1_psip_r_z.html", "structdg_1_1geo_1_1taylor_1_1_psip_r_z" ],
          [ "PsipZ", "structdg_1_1geo_1_1taylor_1_1_psip_z.html", "structdg_1_1geo_1_1taylor_1_1_psip_z" ],
          [ "PsipZZ", "structdg_1_1geo_1_1taylor_1_1_psip_z_z.html", "structdg_1_1geo_1_1taylor_1_1_psip_z_z" ]
        ] ],
        [ "aCylindricalFunctor", "structdg_1_1geo_1_1a_cylindrical_functor.html", "structdg_1_1geo_1_1a_cylindrical_functor" ],
        [ "aRealGenerator2d", "structdg_1_1geo_1_1a_real_generator2d.html", "structdg_1_1geo_1_1a_real_generator2d" ],
        [ "aRealGeneratorX2d", "structdg_1_1geo_1_1a_real_generator_x2d.html", "structdg_1_1geo_1_1a_real_generator_x2d" ],
        [ "BFieldP", "structdg_1_1geo_1_1_b_field_p.html", "structdg_1_1geo_1_1_b_field_p" ],
        [ "BFieldR", "structdg_1_1geo_1_1_b_field_r.html", "structdg_1_1geo_1_1_b_field_r" ],
        [ "BFieldT", "structdg_1_1geo_1_1_b_field_t.html", "structdg_1_1geo_1_1_b_field_t" ],
        [ "BFieldZ", "structdg_1_1geo_1_1_b_field_z.html", "structdg_1_1geo_1_1_b_field_z" ],
        [ "BHatP", "structdg_1_1geo_1_1_b_hat_p.html", "structdg_1_1geo_1_1_b_hat_p" ],
        [ "BHatPR", "structdg_1_1geo_1_1_b_hat_p_r.html", "structdg_1_1geo_1_1_b_hat_p_r" ],
        [ "BHatPZ", "structdg_1_1geo_1_1_b_hat_p_z.html", "structdg_1_1geo_1_1_b_hat_p_z" ],
        [ "BHatR", "structdg_1_1geo_1_1_b_hat_r.html", "structdg_1_1geo_1_1_b_hat_r" ],
        [ "BHatRR", "structdg_1_1geo_1_1_b_hat_r_r.html", "structdg_1_1geo_1_1_b_hat_r_r" ],
        [ "BHatRZ", "structdg_1_1geo_1_1_b_hat_r_z.html", "structdg_1_1geo_1_1_b_hat_r_z" ],
        [ "BHatZ", "structdg_1_1geo_1_1_b_hat_z.html", "structdg_1_1geo_1_1_b_hat_z" ],
        [ "BHatZR", "structdg_1_1geo_1_1_b_hat_z_r.html", "structdg_1_1geo_1_1_b_hat_z_r" ],
        [ "BHatZZ", "structdg_1_1geo_1_1_b_hat_z_z.html", "structdg_1_1geo_1_1_b_hat_z_z" ],
        [ "Bmodule", "structdg_1_1geo_1_1_bmodule.html", "structdg_1_1geo_1_1_bmodule" ],
        [ "BR", "structdg_1_1geo_1_1_b_r.html", "structdg_1_1geo_1_1_b_r" ],
        [ "BZ", "structdg_1_1geo_1_1_b_z.html", "structdg_1_1geo_1_1_b_z" ],
        [ "Constant", "structdg_1_1geo_1_1_constant.html", "structdg_1_1geo_1_1_constant" ],
        [ "CurvatureKappaR", "structdg_1_1geo_1_1_curvature_kappa_r.html", "structdg_1_1geo_1_1_curvature_kappa_r" ],
        [ "CurvatureKappaZ", "structdg_1_1geo_1_1_curvature_kappa_z.html", "structdg_1_1geo_1_1_curvature_kappa_z" ],
        [ "CurvatureNablaBR", "structdg_1_1geo_1_1_curvature_nabla_b_r.html", "structdg_1_1geo_1_1_curvature_nabla_b_r" ],
        [ "CurvatureNablaBZ", "structdg_1_1geo_1_1_curvature_nabla_b_z.html", "structdg_1_1geo_1_1_curvature_nabla_b_z" ],
        [ "CylindricalFunctorsLvl1", "structdg_1_1geo_1_1_cylindrical_functors_lvl1.html", "structdg_1_1geo_1_1_cylindrical_functors_lvl1" ],
        [ "CylindricalFunctorsLvl2", "structdg_1_1geo_1_1_cylindrical_functors_lvl2.html", "structdg_1_1geo_1_1_cylindrical_functors_lvl2" ],
        [ "CylindricalSymmTensorLvl1", "structdg_1_1geo_1_1_cylindrical_symm_tensor_lvl1.html", "structdg_1_1geo_1_1_cylindrical_symm_tensor_lvl1" ],
        [ "CylindricalVectorLvl0", "structdg_1_1geo_1_1_cylindrical_vector_lvl0.html", "structdg_1_1geo_1_1_cylindrical_vector_lvl0" ],
        [ "CylindricalVectorLvl1", "structdg_1_1geo_1_1_cylindrical_vector_lvl1.html", "structdg_1_1geo_1_1_cylindrical_vector_lvl1" ],
        [ "Divb", "structdg_1_1geo_1_1_divb.html", "structdg_1_1geo_1_1_divb" ],
        [ "DivCurvatureKappa", "structdg_1_1geo_1_1_div_curvature_kappa.html", "structdg_1_1geo_1_1_div_curvature_kappa" ],
        [ "DivCurvatureNablaB", "structdg_1_1geo_1_1_div_curvature_nabla_b.html", "structdg_1_1geo_1_1_div_curvature_nabla_b" ],
        [ "DivLiseikinX", "structdg_1_1geo_1_1_div_liseikin_x.html", "structdg_1_1geo_1_1_div_liseikin_x" ],
        [ "DivLiseikinY", "structdg_1_1geo_1_1_div_liseikin_y.html", "structdg_1_1geo_1_1_div_liseikin_y" ],
        [ "DivVVP", "structdg_1_1geo_1_1_div_v_v_p.html", "structdg_1_1geo_1_1_div_v_v_p" ],
        [ "DS", "structdg_1_1geo_1_1_d_s.html", "structdg_1_1geo_1_1_d_s" ],
        [ "DSPGenerator", "structdg_1_1geo_1_1_d_s_p_generator.html", "structdg_1_1geo_1_1_d_s_p_generator" ],
        [ "Fieldaligned", "structdg_1_1geo_1_1_fieldaligned.html", "structdg_1_1geo_1_1_fieldaligned" ],
        [ "FluxGenerator", "structdg_1_1geo_1_1_flux_generator.html", "structdg_1_1geo_1_1_flux_generator" ],
        [ "FluxSurfaceAverage", "structdg_1_1geo_1_1_flux_surface_average.html", "structdg_1_1geo_1_1_flux_surface_average" ],
        [ "FluxSurfaceIntegral", "structdg_1_1geo_1_1_flux_surface_integral.html", "structdg_1_1geo_1_1_flux_surface_integral" ],
        [ "FluxVolumeIntegral", "structdg_1_1geo_1_1_flux_volume_integral.html", "structdg_1_1geo_1_1_flux_volume_integral" ],
        [ "GradLnB", "structdg_1_1geo_1_1_grad_ln_b.html", "structdg_1_1geo_1_1_grad_ln_b" ],
        [ "Hector", "structdg_1_1geo_1_1_hector.html", "structdg_1_1geo_1_1_hector" ],
        [ "Hoo", "structdg_1_1geo_1_1_hoo.html", "structdg_1_1geo_1_1_hoo" ],
        [ "InvB", "structdg_1_1geo_1_1_inv_b.html", "structdg_1_1geo_1_1_inv_b" ],
        [ "LaplacePsip", "structdg_1_1geo_1_1_laplace_psip.html", "structdg_1_1geo_1_1_laplace_psip" ],
        [ "Liseikin_XX", "structdg_1_1geo_1_1_liseikin___x_x.html", "structdg_1_1geo_1_1_liseikin___x_x" ],
        [ "Liseikin_XY", "structdg_1_1geo_1_1_liseikin___x_y.html", "structdg_1_1geo_1_1_liseikin___x_y" ],
        [ "Liseikin_YY", "structdg_1_1geo_1_1_liseikin___y_y.html", "structdg_1_1geo_1_1_liseikin___y_y" ],
        [ "LnB", "structdg_1_1geo_1_1_ln_b.html", "structdg_1_1geo_1_1_ln_b" ],
        [ "LogPolarGenerator", "structdg_1_1geo_1_1_log_polar_generator.html", "structdg_1_1geo_1_1_log_polar_generator" ],
        [ "MagneticFieldParameters", "structdg_1_1geo_1_1_magnetic_field_parameters.html", "structdg_1_1geo_1_1_magnetic_field_parameters" ],
        [ "NablaPsiInv", "structdg_1_1geo_1_1_nabla_psi_inv.html", "structdg_1_1geo_1_1_nabla_psi_inv" ],
        [ "NablaPsiInvX", "structdg_1_1geo_1_1_nabla_psi_inv_x.html", "structdg_1_1geo_1_1_nabla_psi_inv_x" ],
        [ "NablaPsiInvY", "structdg_1_1geo_1_1_nabla_psi_inv_y.html", "structdg_1_1geo_1_1_nabla_psi_inv_y" ],
        [ "Periodify", "structdg_1_1geo_1_1_periodify.html", "structdg_1_1geo_1_1_periodify" ],
        [ "PolarGenerator", "structdg_1_1geo_1_1_polar_generator.html", "structdg_1_1geo_1_1_polar_generator" ],
        [ "RealCurvilinearGrid2d", "structdg_1_1geo_1_1_real_curvilinear_grid2d.html", "structdg_1_1geo_1_1_real_curvilinear_grid2d" ],
        [ "RealCurvilinearGridX2d", "structdg_1_1geo_1_1_real_curvilinear_grid_x2d.html", "structdg_1_1geo_1_1_real_curvilinear_grid_x2d" ],
        [ "RealCurvilinearMPIGrid2d", "structdg_1_1geo_1_1_real_curvilinear_m_p_i_grid2d.html", "structdg_1_1geo_1_1_real_curvilinear_m_p_i_grid2d" ],
        [ "RealCurvilinearProductGrid3d", "structdg_1_1geo_1_1_real_curvilinear_product_grid3d.html", "structdg_1_1geo_1_1_real_curvilinear_product_grid3d" ],
        [ "RealCurvilinearProductGridX3d", "structdg_1_1geo_1_1_real_curvilinear_product_grid_x3d.html", "structdg_1_1geo_1_1_real_curvilinear_product_grid_x3d" ],
        [ "RealCurvilinearProductMPIGrid3d", "structdg_1_1geo_1_1_real_curvilinear_product_m_p_i_grid3d.html", "structdg_1_1geo_1_1_real_curvilinear_product_m_p_i_grid3d" ],
        [ "RealCurvilinearRefinedGridX2d", "structdg_1_1geo_1_1_real_curvilinear_refined_grid_x2d.html", "structdg_1_1geo_1_1_real_curvilinear_refined_grid_x2d" ],
        [ "RealCurvilinearRefinedProductGridX3d", "structdg_1_1geo_1_1_real_curvilinear_refined_product_grid_x3d.html", "structdg_1_1geo_1_1_real_curvilinear_refined_product_grid_x3d" ],
        [ "RealCylindricalFunctor", "structdg_1_1geo_1_1_real_cylindrical_functor.html", "structdg_1_1geo_1_1_real_cylindrical_functor" ],
        [ "RhoP", "structdg_1_1geo_1_1_rho_p.html", "structdg_1_1geo_1_1_rho_p" ],
        [ "Ribeiro", "structdg_1_1geo_1_1_ribeiro.html", "structdg_1_1geo_1_1_ribeiro" ],
        [ "RibeiroFluxGenerator", "structdg_1_1geo_1_1_ribeiro_flux_generator.html", "structdg_1_1geo_1_1_ribeiro_flux_generator" ],
        [ "RibeiroX", "structdg_1_1geo_1_1_ribeiro_x.html", "structdg_1_1geo_1_1_ribeiro_x" ],
        [ "SafetyFactor", "structdg_1_1geo_1_1_safety_factor.html", "structdg_1_1geo_1_1_safety_factor" ],
        [ "SafetyFactorAverage", "structdg_1_1geo_1_1_safety_factor_average.html", "structdg_1_1geo_1_1_safety_factor_average" ],
        [ "ScalarProduct", "structdg_1_1geo_1_1_scalar_product.html", "structdg_1_1geo_1_1_scalar_product" ],
        [ "SeparatrixOrthogonal", "structdg_1_1geo_1_1_separatrix_orthogonal.html", "structdg_1_1geo_1_1_separatrix_orthogonal" ],
        [ "SeparatrixOrthogonalAdaptor", "structdg_1_1geo_1_1_separatrix_orthogonal_adaptor.html", "structdg_1_1geo_1_1_separatrix_orthogonal_adaptor" ],
        [ "SimpleOrthogonal", "structdg_1_1geo_1_1_simple_orthogonal.html", "structdg_1_1geo_1_1_simple_orthogonal" ],
        [ "SquareNorm", "structdg_1_1geo_1_1_square_norm.html", "structdg_1_1geo_1_1_square_norm" ],
        [ "TokamakMagneticField", "structdg_1_1geo_1_1_tokamak_magnetic_field.html", "structdg_1_1geo_1_1_tokamak_magnetic_field" ],
        [ "Topology1d", "structdg_1_1geo_1_1_topology1d.html", "structdg_1_1geo_1_1_topology1d" ],
        [ "TrueCurvatureKappaP", "structdg_1_1geo_1_1_true_curvature_kappa_p.html", "structdg_1_1geo_1_1_true_curvature_kappa_p" ],
        [ "TrueCurvatureKappaR", "structdg_1_1geo_1_1_true_curvature_kappa_r.html", "structdg_1_1geo_1_1_true_curvature_kappa_r" ],
        [ "TrueCurvatureKappaZ", "structdg_1_1geo_1_1_true_curvature_kappa_z.html", "structdg_1_1geo_1_1_true_curvature_kappa_z" ],
        [ "TrueCurvatureNablaBP", "structdg_1_1geo_1_1_true_curvature_nabla_b_p.html", "structdg_1_1geo_1_1_true_curvature_nabla_b_p" ],
        [ "TrueCurvatureNablaBR", "structdg_1_1geo_1_1_true_curvature_nabla_b_r.html", "structdg_1_1geo_1_1_true_curvature_nabla_b_r" ],
        [ "TrueCurvatureNablaBZ", "structdg_1_1geo_1_1_true_curvature_nabla_b_z.html", "structdg_1_1geo_1_1_true_curvature_nabla_b_z" ],
        [ "TrueDivCurvatureKappa", "structdg_1_1geo_1_1_true_div_curvature_kappa.html", "structdg_1_1geo_1_1_true_div_curvature_kappa" ],
        [ "TrueDivCurvatureNablaB", "structdg_1_1geo_1_1_true_div_curvature_nabla_b.html", "structdg_1_1geo_1_1_true_div_curvature_nabla_b" ],
        [ "WallDirection", "structdg_1_1geo_1_1_wall_direction.html", "structdg_1_1geo_1_1_wall_direction" ],
        [ "WallFieldlineCoordinate", "structdg_1_1geo_1_1_wall_fieldline_coordinate.html", "structdg_1_1geo_1_1_wall_fieldline_coordinate" ],
        [ "WallFieldlineDistance", "structdg_1_1geo_1_1_wall_fieldline_distance.html", "structdg_1_1geo_1_1_wall_fieldline_distance" ],
        [ "ZCutter", "structdg_1_1geo_1_1_z_cutter.html", "structdg_1_1geo_1_1_z_cutter" ]
      ] ]
    ] ]
];